# Generated by Django 3.2.18 on 2023-11-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231122_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='users_achievemnt', to='users.Achievement', verbose_name='Достижения'),
        ),
    ]
