# Generated by Django 3.2.18 on 2023-11-24 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='timedate',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 23, 14, 39, 52151), verbose_name='Дата оформления'),
        ),
    ]
