# Generated by Django 3.2.18 on 2023-11-24 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='timedate',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 23, 42, 10, 67049), verbose_name='Дата оформления'),
        ),
    ]
