# Generated by Django 3.2.18 on 2023-11-25 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_new_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='timedate',
            field=models.DateField(default=datetime.datetime(2023, 11, 25, 23, 44, 59, 985518), verbose_name='Дата оформления'),
        ),
    ]
