# Generated by Django 3.2.18 on 2023-11-25 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_new_timedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AlterField(
            model_name='new',
            name='timedate',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 0, 21, 14, 899231), verbose_name='Дата оформления'),
        ),
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news_tag', to='news.tag', verbose_name='Тэг'),
            preserve_default=False,
        ),
    ]
