# Generated by Django 3.2.18 on 2023-11-25 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20231126_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='timedate',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 0, 41, 18, 763496), verbose_name='Дата оформления'),
        ),
    ]
