# Generated by Django 3.2.18 on 2023-11-25 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_new_timedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='timedate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 0, 56, 58, 59240), verbose_name='Дата оформления'),
        ),
    ]
