# Generated by Django 3.2.18 on 2023-11-24 21:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import sections.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=sections.models.Category.get_path, verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(blank=True, null=True, verbose_name='Тема')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('date', models.DateField(default=datetime.date(2023, 11, 25), verbose_name='Дата')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('total_students', models.IntegerField(default=0, verbose_name='Всего студентов')),
                ('max_students', models.IntegerField(default=0, verbose_name='Максимально студентов')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('date', models.DateField(default=datetime.date(2023, 11, 25), verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Домашняя работа',
                'verbose_name_plural': 'Домашние работы',
            },
        ),
        migrations.CreateModel(
            name='HomeworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип ДЗ',
                'verbose_name_plural': 'Типы ДЗ',
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=255, null=True, verbose_name='Отчество')),
                ('passport', models.TextField(verbose_name='Пасспорт')),
            ],
            options={
                'verbose_name': 'Законный представитель',
                'verbose_name_plural': 'Законные представители',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(verbose_name='День недели')),
                ('start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время начала')),
                ('end_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время конца')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Средняя оценка секции')),
                ('comments', models.IntegerField(default=0, verbose_name='Комментарии')),
                ('author', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель секции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_category', to='sections.category', verbose_name='Категория')),
                ('grades', models.ManyToManyField(blank=True, related_name='sections_grade', to='sections.Grade', verbose_name='Оценки')),
                ('groups', models.ManyToManyField(blank=True, related_name='sections_group', to='sections.Group', verbose_name='Группы')),
                ('homeworks', models.ManyToManyField(blank=True, related_name='sections_homework', to='sections.Homework', verbose_name='ДЗ')),
                ('students', models.ManyToManyField(blank=True, related_name='sections_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='homework_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_homeworktype', to='sections.homeworktype', verbose_name='Тип ДЗ'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedules',
            field=models.ManyToManyField(related_name='groups_schedule', to='sections.Schedule', verbose_name='Ячейки расписаний'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=sections.models.Application.get_path, verbose_name='Документ')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтвеждена')),
                ('open', models.BooleanField(default=True, verbose_name='Открытая')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_group', to='sections.group', verbose_name='Группа')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_representative', to='sections.representative', verbose_name='Законный представитель')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_section', to='sections.section', verbose_name='Секция')),
                ('student', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
