# Generated by Django 3.2.18 on 2023-11-25 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='schedules',
            field=models.ManyToManyField(blank=True, related_name='groups_schedule', to='sections.Schedule', verbose_name='Ячейки расписаний'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
    ]
