# Generated by Django 3.2.18 on 2023-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20231125_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='parlor',
            field=models.TextField(blank=True, verbose_name='Кабинет'),
        ),
    ]
